#!/bin/bash

echo "🚀 Persona Centric Platform Deployment Guide"
echo "=============================================="
echo ""

echo "📋 Prerequisites:"
echo "1. GitHub repository pushed and up to date"
echo "2. Railway account (railway.app)"
echo "3. Vercel account (vercel.com)"
echo ""

echo "🔧 Step 1: Deploy Backend to Railway"
echo "-------------------------------------"
echo "1. Go to https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select: web_personacentric"
echo "5. Add PostgreSQL database"
echo "6. Set environment variables:"
echo "   - NODE_ENV=production"
echo "   - PORT=5001"
echo "   - JWT_SECRET=your_super_secret_jwt_key_here"
echo "   - CORS_ORIGIN=https://your-vercel-domain.vercel.app"
echo ""

echo "🌐 Step 2: Deploy Frontend to Vercel"
echo "-------------------------------------"
echo "1. Go to https://vercel.com"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project'"
echo "4. Import: web_personacentric"
echo "5. Configure build settings:"
echo "   - Framework Preset: Create React App"
echo "   - Root Directory: client"
echo "   - Build Command: npm run build"
echo "   - Output Directory: build"
echo ""

echo "🔗 Step 3: Connect Frontend to Backend"
echo "---------------------------------------"
echo "1. Get your Railway backend URL"
echo "2. In Vercel, add environment variable:"
echo "   - REACT_APP_API_URL=https://your-railway-domain.railway.app/api"
echo "3. Redeploy frontend"
echo ""

echo "✅ Step 4: Test Deployment"
echo "---------------------------"
echo "1. Test backend health: https://your-railway-domain.railway.app/api/health"
echo "2. Test frontend: https://your-vercel-domain.vercel.app"
echo "3. Test login functionality"
echo ""

echo "🎉 Deployment Complete!"
echo "======================="
echo "Frontend: https://your-vercel-domain.vercel.app"
echo "Backend: https://your-railway-domain.railway.app"
echo ""
echo "📚 Documentation:"
echo "- README.md - Project overview"
echo "- DEPLOYMENT.md - Detailed deployment guide"
echo "" 