[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
  'rm -rf node_modules client/node_modules package-lock.json client/package-lock.json',
  'npm install',
  'cd client && npm install'
]

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'npm start'
