import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Alias for useTranslation to maintain compatibility
export const useTranslation = useLanguage;

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'zh-TW';
  });

  const translations = {
    'zh-TW': {
      // Lifestyle Options
      'lifestyle.active': '活躍型',
      'lifestyle.family': '家庭導向',
      'lifestyle.traveler': '旅遊愛好者',
      'lifestyle.foodie': '美食家',
      'lifestyle.creative': '創意型',
      'lifestyle.tech': '科技迷',
      'lifestyle.wellness': '健康生活',
      'lifestyle.finance': '理財達人',
      'lifestyle.student': '學生族',
      'lifestyle.retiree': '退休族',

      // Events Page
      'events.title': '活動',
      'events.description': '參與活動，認識新朋友，得到財務自由!',
      'events.upcoming': '即將舉行',
      'events.past': '過往活動',
      'events.noUpcoming': '暫無即將舉行的活動',
      'events.noPast': '暫無過往活動',
      'events.checkBackLater': '請稍後再來查看新活動',
      'events.noPastEvents': '目前沒有過往活動記錄',
      'events.registered': '人已報名',
      'events.register': '立即報名',
      'events.cancelRegistration': '取消報名',
      'events.loginToRegister': '登入以報名',
      'events.details': '活動詳情',
      'events.dateAndTime': '日期和時間',
      'events.locationAndCapacity': '地點和容量',
      'events.pricingAndRewards': '定價和獎勵',
      'events.price': '價格',
      'events.free': '免費',
      'events.pointsReward': '積分獎勵',
      'events.points': '積分',
      'events.participants': '參與者',
      
      // Event Types
      'events.workshop': '工作坊',
      'events.seminar': '研討會',
      'events.consultation': '諮詢',
      'events.webinar': '網路研討會',
      
      // Homepage - Events
      'events.financialPlanning': '財務規劃工作坊',
      'events.investmentStrategy': '投資策略研討會',
      'events.retirementPlanning': '退休規劃大師班',
      'events.revisit': '重新瀏覽',
      'events.viewAll': '查看所有活動',

      // Homepage - Partners
      'partners.title': '夥伴',

      // Homepage - Blogs
      'blogs.title': '市場資訊',
      'blogs.investmentStrategies2024': '2024年投資策略',
      'blogs.investmentStrategiesExcerpt': '探索2024年最新的投資趨勢和機會，幫助您做出明智的投資決策。',
      'blogs.insurancePolicies': '了解保險政策',
      'blogs.insurancePoliciesExcerpt': '深入解析各類保險產品，協助您選擇最適合的保障方案。',
      'blogs.retirementEssentials': '退休規劃要點',
      'blogs.retirementEssentialsExcerpt': '掌握退休規劃的關鍵要素，確保您的退休生活無憂無慮。',
      'blogs.readMore': '閱讀更多',
      'blogs.viewAll': '查看所有文章',

      // Homepage - Become a Member
      'member.title': '成為會員',
      'member.subtitle': '登記馬上獲得1,000積分',
      'member.cta': '立即註冊',

      // Homepage - Hero Section
      'home.hero.registerNow': '立即報名留位',
      
      // Homepage - About Section
      'home.about.title': 'Persona Centric是什麼？',
      'home.about.subtitle': '活動，換獎品，識朋友，長知識',
      'home.about.benefit1.title': '理財拍檔智能配對',
      'home.about.benefit1.desc': 'AI技術，匹配最適合您的財務顧問',
      'home.about.benefit2.title': '活動',
      'home.about.benefit2.desc': '參加活動，認識新朋友，贏取獎品',
      'home.about.benefit3.title': '積分遊戲',
      'home.about.benefit3.desc': '參與活動，獲積分及禮品優惠',
      'home.about.benefit4.title': '知識庫',
      'home.about.benefit4.desc': '最新財經知識，投資策略',
      'home.gifts.title': '積分問答',
      'home.gifts.subtitle': '獲得免費禮品！（本月大獎iPhone16）',
      'home.gifts.cta': '登記立即獲得10000積分',
      'home.match.title': '5個問題',
      'home.match.subtitle': '配對最適合您的財務規劃師',
      'home.match.cta': '立即配對',
      'home.events.title': '活動',
      'home.events.cta': '立即加入',
      'home.hero.title': 'Food for Talk',
      'home.hero.eventDate': '10月 2025',
      'home.gifts.description': '完成問卷，贏取豐富獎品',
      'home.gifts.participate': '立即參與',
      'home.events.description': '參與活動，識朋友，長知識',
      'partners.placeholder': '合作夥伴 {number}',

      // Homepage - Small CTA
      'home.getRightAgent': 'AI技術，匹配最適合您的財務顧問',
      'smallCTA.button': '開始配對',

      // Homepage - Stats
      'home.proofOfConcept': '概念驗證',
      'footer.followUs': 'Follow Us',
      'footer.socialMedia.facebook': 'Follow us on Facebook',
      'footer.socialMedia.instagram': 'Follow us on Instagram',
      'footer.socialMedia.linkedin': 'Connect on LinkedIn',
      'footer.socialMedia.twitter': 'Follow us on Twitter',
      'home.realResults': '我們平台的真實成果',
      'stats.agents': '位顧問',
      'stats.clients': '位成功客戶',
      'stats.growth': '投資成長率',
      'stats.activeAdvisors': '活躍財務顧問',
      'stats.successfulClients': '成功服務的客戶',
      'stats.averageGrowth': '平均投資成長率',

      // Contest Winners
      'contest.winners.socialMedia': '社群媒體貼文',
      'contest.winners.blogArticle': '部落格文章',
      'contest.winners.posterDesign': '海報設計',
      'contest.winners.videoContent': '影片內容',
      'contest.winners.bestViralPost': '關於財務素養的最佳病毒貼文',
      'contest.winners.insightfulBlog': '關於投資策略的深入部落格',
      'contest.winners.creativePoster': '退休規劃創意海報',
      'contest.winners.engagingVideo': '保險基礎知識吸引影片',

      // Financial Planning - Main
      'financialPlanning.title': '理財產品配置',
      'financialPlanning.tab': '理財產品配置',
      'financialPlanning.page1': '產品配置',
      'financialPlanning.page2': '財務分析',
      'financialPlanning.create': '創建',
      'financialPlanning.loadSaved': '載入已保存',
      'financialPlanning.save': '保存',
      'financialPlanning.cancel': '取消',
      'financialPlanning.close': '關閉',
      'financialPlanning.back': '返回',
      'financialPlanning.next': '下一步',
      'financialPlanning.previous': '上一步',
      'financialPlanning.load': '載入',

      // Product Categories
      'financialPlanning.selectCategory': '選擇產品類別',
      'financialPlanning.investment': '投資',
      'financialPlanning.saving': '儲蓄',
      'financialPlanning.realEstate': '房地產',
      'financialPlanning.selectProduct': '選擇產品類型',
      'financialPlanning.funds': '基金',
      'financialPlanning.mpf': '強積金',
      'financialPlanning.savingPlans': '儲蓄計劃',
      'financialPlanning.bank': '銀行',
      'financialPlanning.annuity': '年金',
      'financialPlanning.ownLiving': '自住',
      'financialPlanning.rental': '租賃',

      // Product Management
      'financialPlanning.product': '產品',
      'financialPlanning.addProduct': '添加產品',
      'financialPlanning.removeProduct': '移除產品',
      'financialPlanning.duplicateProduct': '複製產品',
      'financialPlanning.noProducts': '尚未添加任何產品',
      'financialPlanning.noProductsDescription': '點擊「創建」開始添加理財產品',

      // User Management
      'financialPlanning.loadUser': '載入用戶',
      'financialPlanning.noSavedUsers': '沒有保存的用戶',
      'financialPlanning.noSavedUsersDescription': '請先創建並保存用戶的理財產品配置',

      // Financial Analysis
      'financialPlanning.financialAnalysis': '財務分析設定',
      'financialPlanning.retirementAge': '退休年齡',
      'financialPlanning.inflationRate': '通脹率 (%)',
      'financialPlanning.currentAssets': '當前資產 (HKD)',
      'financialPlanning.analysisPeriod': '分析期間',
      'financialPlanning.to': '至',
      'financialPlanning.recalculate': '重新計算',
      'financialPlanning.calculating': '計算中...',
      'financialPlanning.startAnalysis': '開始財務分析',
      'financialPlanning.startAnalysisDescription': '設定您的財務參數並點擊「重新計算」開始分析',
      'financialPlanning.startAnalysisButton': '開始分析',

      // Expenses
      'financialPlanning.expenses': '開支設定',
      'financialPlanning.addExpenseStage': '添加開支階段',
      'financialPlanning.ageFrom': '年齡從',
      'financialPlanning.ageTo': '年齡至',
      'financialPlanning.monthlyExpenses': '月開支',
      'financialPlanning.removeExpense': '移除開支',

      // Results Table
      'financialPlanning.annualFinancialStatus': '年度財務狀況',
      'financialPlanning.age': '年齡',
      'financialPlanning.totalMonthlyIncome': '總月收入',
      'financialPlanning.passiveIncome': '被動收入',
      'financialPlanning.totalExpenses': '月開支',
      'financialPlanning.netCashFlow': '淨現金流',
      'financialPlanning.totalAssets': '總資產',
      'financialPlanning.totalLiabilities': '總負債',
      'financialPlanning.netWorth': '淨資產',
      'financialPlanning.accumulatedFlexibleFunds': '年度靈活資金',

      // Charts
      'financialPlanning.financialTrendChart': '財務趨勢圖',
      'financialPlanning.assetAllocation': '資產配置',
      'financialPlanning.incomeSourcesAnalysis': '收入來源分析',
      'financialPlanning.selectAge': '選擇年齡',
      'financialPlanning.yearsOld': '歲',
      'financialPlanning.property': '物業',
      'financialPlanning.cash': '現金',
      'financialPlanning.investments': '投資',
      'financialPlanning.other': '其他',
      'financialPlanning.flexibleFunds': '年度靈活資金',
      'financialPlanning.workIncome': '工作收入',
      'financialPlanning.investmentIncome': '投資收入',
      'financialPlanning.fundIncome': '基金收益',
      'financialPlanning.mpfIncome': '強積金',
      'financialPlanning.savingIncome': '儲蓄計劃',
      'financialPlanning.bankIncome': '銀行利息',
      'financialPlanning.bankReturn': '銀行回報',
      'financialPlanning.annuityIncome': '年金收入',
      'financialPlanning.rentalIncome': '租金收入',
      'financialPlanning.incomeSources': '收入來源 (HKD)',
      'financialPlanning.annualIncomeSources': '各收入來源年度金額',
      'financialPlanning.netWorthPassiveIncomeExpenses': '淨資產、被動收入與開支趨勢',

      // Formula Info
      'financialPlanning.viewChartExplanation': '查看圖表說明',
      'financialPlanning.viewCalculationFormula': '查看計算公式',
      'financialPlanning.formulaExplanation': '計算公式：',
      'financialPlanning.description': '說明：',
      'financialPlanning.unknown': '未知',
      'financialPlanning.noFormula': '無公式',
      'financialPlanning.noDescription': '無描述',

      // PDF Report
      'financialPlanning.pdfReport': 'PDF 報告',
      'financialPlanning.client': '客戶',
      'financialPlanning.downloadPDF': '下載 PDF',
      'financialPlanning.financialPlanningReport': '理財產品配置報告',
      'financialPlanning.preparedFor': '為客戶準備',
      'financialPlanning.reportDate': '報告日期',
      'financialPlanning.executiveSummary': '執行摘要',
      'financialPlanning.configuredProducts': '已配置產品',
      'financialPlanning.productConfiguration': '產品配置',
      'financialPlanning.productType': '產品類型',
      'financialPlanning.details': '詳細資料',
      'financialPlanning.projectedValue': '預期價值',
      'financialPlanning.investmentAmount': '投資金額',
      'financialPlanning.expectedReturn': '預期回報',
      'financialPlanning.monthlySalary': '月薪',
      'financialPlanning.contribution': '供款',
      'financialPlanning.monthly': '月',
      'financialPlanning.interestRate': '利率',
      'financialPlanning.purchasePrice': '購買價格',
      'financialPlanning.rentalExpenses': '租金開支',
      'financialPlanning.rentAmount': '租金收入',
      'financialPlanning.noDetails': '無詳細資料',
      'financialPlanning.recommendations': '建議',
      'financialPlanning.recommendation1': '定期檢視和調整您的投資組合以符合市場變化',
      'financialPlanning.recommendation2': '考慮增加退休儲蓄以確保退休後的生活品質',
      'financialPlanning.recommendation3': '多元化投資以分散風險並提高回報潛力',
      'financialPlanning.recommendation4': '定期與財務顧問會面以檢討和優化您的財務計劃',
      'financialPlanning.reportFooter1': '本報告僅供參考，不構成投資建議',
      'financialPlanning.reportFooter2': '請諮詢專業財務顧問以獲得個人化的投資建議',
      'financialPlanning.chartPlaceholder': '圖表佔位符',
      'financialPlanning.clientName': '客戶姓名',
      'financialPlanning.enterClientName': '輸入客戶姓名',
      'financialPlanning.generateReport': '生成報告',
      'financialPlanning.reportGenerated': '報告已生成',
      'financialPlanning.reportGenerationFailed': '報告生成失敗',

      // Recommendations Editor
      'financialPlanning.editRecommendations': '編輯建議',
      'financialPlanning.resetToDefault': '重置為預設',
      'financialPlanning.recommendationsDescription': '自定義您的財務規劃建議。這些建議將顯示在PDF報告中，為客戶提供專業的財務指導。',
      'financialPlanning.enterRecommendation': '輸入建議內容...',
      'financialPlanning.removeRecommendation': '移除建議',
      'financialPlanning.addRecommendation': '添加建議',
      'financialPlanning.recommendationsPreview': '建議預覽',
      'financialPlanning.emptyRecommendation': '（空建議）',
      'financialPlanning.editRecommendationsButton': '編輯建議',

      // Report Generation Section
      'financialPlanning.reportGeneration': '報告生成',
      'financialPlanning.reportGenerationDescription': '生成包含所有財務規劃數據的專業PDF報告。請確保所有必要信息已完成。',
      'financialPlanning.completed': '已完成',
      'financialPlanning.required': '需要完成',
      'financialPlanning.products': '產品配置',

      // Product Card Fields - Funds
      'productCard.fundAllocation': '基金配置',
      'productCard.growth': '增長型',
      'productCard.dividends': '股息型',
      'productCard.investmentAmount': '投資金額 (HKD)',
      'productCard.startAge': '開始年齡',
      'productCard.expectedReturn': '預期年回報率 (%)',
      'productCard.expectedReturnPlaceholder': '例如: 8 表示年回報率 8%',
      'productCard.expectedWithdrawalAge': '預期提取年齡',
      'productCard.expectedWithdrawalAgePlaceholder': '例如: 65 表示65歲時提取',
      'productCard.fundCategory': '基金類別',
      'productCard.growthFund': '增長基金',
      'productCard.dividendFund': '派息基金',
      'productCard.monthlyDividends': '每月派息',
      'productCard.yearlyDividends': '年度累積派息',
      'productCard.totalDividends': '累積派息至提取年齡',
      'productCard.totalReturn': '退保時總回報',
      'productCard.compoundCalculation': '複式計算',
      'productCard.simpleCalculation': '單利計算',

      // Product Card Fields - MPF
      'productCard.monthlySalary': '月薪 (HKD)',
      'productCard.salaryIncrement': '年薪增幅 (%)',
      'productCard.employerContribution': '僱主供款 (%)',
      'productCard.employeeContribution': '僱員供款 (%)',
      'productCard.currentAge': '當前年齡',
      'productCard.currentMPFAmount': '現有強積金金額',
      'productCard.mpfAt65': '65歲時強積金總額',
      'productCard.totalDividendsEarned': '總派息收益',
      'productCard.mpfWithoutDividends': '無派息時強積金價值',
      'productCard.employeeContributionDeduction': '僱員供款扣除',

      // Product Card Fields - Saving Plans
      'productCard.planName': '計劃名稱',
      'productCard.contribution': '供款金額',
      'productCard.contributionType': '供款頻率',
      'productCard.monthly': '每月',
      'productCard.yearly': '每年',
      'productCard.contributionDuration': '供款年期',
      'productCard.surrenderAge': '退保年齡',
      'productCard.planType': '計劃類型',
      'productCard.duration': '年期',
      'productCard.interestRate': '利率 (%)',
      'productCard.withdrawalAge': '提取年齡',
      'productCard.contributionAmount': '供款金額',
      'productCard.frequency': '供款頻率',
      'productCard.startDate': '開始日期',
      'productCard.targetRetirementAge': '目標退休年齡',
      'productCard.expectedAnnualReturn': '預期年回報率 (%)',
      'productCard.breakEvenPeriod': '回本期(年)',
      'productCard.withdrawalAmount': '金額提取',
      'productCard.withdrawalPeriod': '提取金額年期',
      'productCard.surrenderValue': '退保金額',
      'productCard.contributionPeriod': '供款年期',

      // Product Card Fields - Bank
      'productCard.saving': '儲蓄 (靈活資金)',
      'productCard.fixedDeposit': '定期存款',
      'productCard.existingAmount': '現存金額',
      'productCard.contributionFrequency': '供款頻率',
      'productCard.alreadyOwned': '已擁有金額',
      'productCard.yes': '是',
      'productCard.no': '否',
      'productCard.lockInPeriod': '資金鎖定時間(月)',
      'productCard.totalSavings': '總儲蓄金額',
      'productCard.totalAmount': '總金額',

      // Product Card Fields - Own Living
      'productCard.purchasePrice': '購買價格 (HKD)',
      'productCard.downPayment': '首期付款 (%)',
      'productCard.downPaymentPlaceholder': '例如: 30',
      'productCard.mortgageStartAge': '開始供樓年紀',
      'productCard.currentSituation': '現況',
      'productCard.selfOccupied': '自住',
      'productCard.renting': '租賃',
      'productCard.monthlyRent': '月租 (HKD)',
      'productCard.rentStartAge': '租約開始年齡',
      'productCard.rentIncreaseRate': '租金增幅 (%)',
      'productCard.monthlyPayment': '每月供款',
      'productCard.sellAge': '賣樓年紀',
      'productCard.willNotSell': '不會賣',
      'productCard.willSell': '將會售樓',
      'productCard.sellAgePlaceholder': '例如: 65',
      'productCard.mortgageInterestRate': '按揭利率 (%)',
      'productCard.mortgageInterestRatePlaceholder': '例如: 3.5',
      'productCard.mortgageCompletionAge': '供完樓年齡',
      'productCard.mortgageCompletionAgePlaceholder': '例如: 60',
      'productCard.totalInterestPaid': '總利息支出',
      'productCard.propertyValueAtCompletion': '供完樓時物業價值',
      'productCard.propertyValueGrowth': '物業價值增長 (%)',
      'productCard.propertyValueGrowthPlaceholder': '例如: 1.0',
      'productCard.propertyValueAtAge': '{age}歲時物業價值',
      'productCard.saleProceeds': '售樓收益',

      // Product Card Fields - Rental
      'productCard.monthlyRentExpense': '每月租金開支 (HKD)',
      'productCard.leaseStartAge': '租約開始年齡',
      'productCard.rentIncreaseRatePlaceholder': '例如: 3',
      'productCard.expectedEndAge': '預期結束年齡',
      'productCard.totalRentPaid': '總租金支出',

      // Product Card Fields - Annuity
      'productCard.annuityType': '年金類型',
      'productCard.deferred': '延期',
      'productCard.immediate': '即期',
      'productCard.annualContribution': '每年供款額 (HKD)',
      'productCard.annualContributionPlaceholder': '例如: 100000',
      'productCard.contributionAmountPlaceholder': '例如: 1000000',
      'productCard.gender': '性別',
      'productCard.male': '男性',
      'productCard.female': '女性',
      'productCard.annuityStartAge': '年金開始年齡',
      'productCard.premiumAge': '投保年齡',
      'productCard.lifeExpectancy': '預期壽命',
      'productCard.monthlyAnnuity': '每月年金',
      'productCard.totalAnnuityIncome': '總年金收入',
      'productCard.internalRateOfReturn': '內部回報率',

      // Product Card - Common
      'productCard.removeProduct': '移除產品',
      'productCard.duplicateProduct': '複製產品',
      'productCard.summary': '摘要',
      'productCard.unknownProductType': '未知產品類型',
      'productCard.productNumber': '產品 #',
      'productCard.copyProduct': '複製產品',
      'productCard.deleteProduct': '刪除產品',

      // Info Dialog
      'productCard.viewFormula': '查看計算公式',
      'productCard.calculationFormula': '計算公式',
      'productCard.explanation': '說明',

      // Dashboard
      'dashboard.tabs.overview': '概覽',
      'dashboard.tabs.agentConnection': '客戶配對',
      'dashboard.tabs.events': '活動',
      'dashboard.tabs.blogManagement': '博客管理',
      'dashboard.tabs.points': '積分',
      'dashboard.tabs.contests': '競賽',
      'dashboard.tabs.profile': '個人資料',
      'dashboard.tabs.financial_planning': '理財產品配置',

      // Navigation
      'nav.events': '活動',
      'nav.agentPairing': '客戶配對',
      'nav.contentGenerator': '內容生成器',
      'nav.blogs': '博客',
      'nav.about': '關於我們',
      'nav.login': '登入',
      'nav.register': '註冊',

      // Actions
      'actions.allAgents': '所有代理',
      'actions.dashboard': '儀表板',
      'actions.logout': '登出',

      // Agent Matching
      'matching.title': '智能客戶配對系統',
      'matching.subtitle': '回答幾個簡單問題，我們將為您找到最適合的財務顧問',
      'matching.previous': '上一題',
      'matching.next': '下一題',
      'matching.finish': '完成配對',
      'matching.retake': '重新測試',
      'matching.viewAllAgents': '查看所有顧問',
      'matching.yourPerfectMatches': '您的完美配對',
      'matching.basedOnAnswers': '根據您的答案，以下是最適合幫助您實現財務目標的顧問。',
      'matching.matching': '配對中...',
      'matching.match': '配對',
      'matching.matchHighlights': '配對優勢',
      'matching.contactNow': '立即聯繫',
      'matching.viewFullProfile': '查看完整資料',
      'matching.whyUseOurSystem': '為什麼使用我們的配對系統？',
      'matching.preciseMatching': '精確配對',
      'matching.preciseMatchingDesc': 'AI驅動算法找到符合您特定需求和偏好的顧問',
      'matching.saveTime': '節省時間',
      'matching.saveTimeDesc': '跳過研究，在幾分鐘內與合格顧問配對',
      'matching.verifiedAdvisors': '驗證顧問',
      'matching.verifiedAdvisorsDesc': '所有顧問都是經過驗證的專業人士，擁有證實的記錄',

      // About Us
      'about.title': '關於 Persona Centric',
      'about.subtitle': '重新定義財務規劃的未來',
      'about.hero.title': '您的完美財務顧問',
      'about.hero.subtitle': '智能配對、活動體驗和積分獎勵，實現您的財務目標',
      'about.hero.cta': '立即成為會員',
      'about.hero.learnMore': '了解更多',
      'about.mission.title': '使命',
      'about.mission.subtitle': '讓每個人都能找到最適合的財務顧問，建立長期信任關係',
      'about.mission.description': '財務規劃不應該被一般化。每個人的財務狀況、目標和風險承受度都不同，因此需要個性化的建議和持續的支持。',
      'about.coreValues.title': '核心價值',
      'about.coreValues.personalized': '個性化配對',
      'about.coreValues.personalizedDesc': 'AI驅動的智能配對系統，根據您的具體需求和偏好找到最適合的財務顧問',
      'about.coreValues.trust': '建立信任',
      'about.coreValues.trustDesc': '真實活動和面對面互動，讓您與顧問建立深厚的信任關係',
      'about.coreValues.engagement': '持續參與',
      'about.coreValues.engagementDesc': '積分系統和獎勵機制，財務策劃變得好玩',
      'about.coreValues.transparency': '透明管理',
      'about.coreValues.transparencyDesc': '一站式服務，讓您清楚掌握自己的投資狀況',
      'about.features.title': '平台特色',
      'about.features.matching.title': '智能顧問配對',
      'about.features.matching.desc': '回答簡單問題，我們將為您找到最適合的財務顧問',
      'about.features.events.title': '真實活動體驗',
      'about.features.events.desc': '參加各種財務活動，在輕鬆環境中認識您的顧問',
      'about.features.points.title': '積分獎勵系統',
      'about.features.points.desc': '完成問卷、參加活動，賺取積分兌換禮品券和好禮',
      'about.features.dashboard.title': '一站式儀表板',
      'about.features.dashboard.desc': '所有投資一目了然，定期更新和專業建議',
      'about.howItWorks.title': '如何使用',
      'about.howItWorks.step1.title': '註冊成為會員',
      'about.howItWorks.step1.desc': '簡單註冊，立即獲得10,000積分',
      'about.howItWorks.step2.title': '完成配對問卷',
      'about.howItWorks.step2.desc': '回答問題，找到最適合的財務顧問',
      'about.howItWorks.step3.title': '參加活動建立關係',
      'about.howItWorks.step3.desc': '透過活動認識顧問，建立信任關係',
      'about.howItWorks.step4.title': '開始財務規劃',
      'about.howItWorks.step4.desc': '獲得個性化建議，追蹤投資進度',
      'about.benefits.title': '會員專享福利',
      'about.benefits.personalized.title': '個性化財務建議',
      'about.benefits.personalized.desc': '根據您的具體情況提供量身定制的財務規劃建議',
      'about.benefits.exclusive.title': '獨家活動優先參與',
      'about.benefits.exclusive.desc': '優先參與各種財務教育活動和研討會',
      'about.benefits.rewards.title': '豐富獎勵系統',
      'about.benefits.rewards.desc': '完成任務賺取積分，兌換各種實用禮品和服務',
      'about.benefits.support.title': '專業持續支持',
      'about.benefits.support.desc': '獲得持續的財務建議和投資組合更新',
      'about.stats.title': '平台數據',
      'about.stats.advisors': '專業顧問',
      'about.stats.members': '活躍會員',
      'about.stats.events': '成功活動',
      'about.stats.satisfaction': '滿意度',
      'about.cta.title': '準備好開始您的財務規劃之旅了嗎？',
      'about.cta.subtitle': '加入我們，找到您的完美財務顧問，實現財務自由',
      'about.cta.register': '立即註冊',
      'about.cta.learnMore': '了解更多',
      'about.team.title': '認識我們的團隊',
      'about.team.subtitle': '一群充滿熱情的理財顧問，致力於為您提供最好的財務規劃服務',
      'about.team.member1.name': '張小明',
      'about.team.member1.role': '創始人 & CEO',
      'about.team.member1.bio': '擁有15年金融科技經驗，致力於讓財務規劃更親民',
      'about.team.member2.name': '李美玲',
      'about.team.member2.role': '首席技術官',
      'about.team.member2.bio': 'AI專家，負責智能配對系統的開發和優化',
      'about.team.member3.name': '王建國',
      'about.team.member3.role': '營運總監',
      'about.team.member3.bio': '活動策劃專家，為會員創造難忘的體驗',
      'about.team.member4.name': '陳雅婷',
      'about.team.member4.role': '客戶成功經理',
      'about.team.member4.bio': '確保每位會員都能獲得最佳的服務體驗',
      'about.giftSystem.title': '🎁 積分獎勵',
      'about.giftSystem.subtitle': '參與越多，獎勵越多！',
      'about.giftSystem.signup.title': '註冊即送',
      'about.giftSystem.signup.points': '10,000 積分',
      'about.giftSystem.signup.desc': '新會員註冊立即獲得豐厚積分',
      'about.giftSystem.earn.title': '賺取積分',
      'about.giftSystem.earn.quiz': '完成問卷',
      'about.giftSystem.earn.event': '參加活動',
      'about.giftSystem.earn.referral': '推薦朋友',
      'about.giftSystem.earn.points': '500-2,000 積分',
      'about.giftSystem.redeem.title': '兌換禮品',
      'about.giftSystem.redeem.desc': '用積分兌換各種精美禮品和禮品卡',
      'about.giftSystem.featured.title': '熱門禮品',
      'about.giftSystem.featured.airpods': 'Apple AirPods Pro',
      'about.giftSystem.featured.coffee': '高級咖啡機',
      'about.giftSystem.featured.giftcard': 'HKD50 活動禮券',
      'about.giftSystem.cta': '立即查看禮品目錄',
      'about.liveActivity.title': '🔥 即時動態',
      'about.liveActivity.subtitle': '看看我們的會員正在做什麼',
      'about.liveActivity.member1': '張小明 剛剛完成了財務健康問卷 +500積分',
      'about.liveActivity.member2': '李美玲 參加了投資理財講座 +1,000積分',
      'about.liveActivity.member3': '王建國 兌換了Apple AirPods Pro -5,000積分',
      'about.liveActivity.member4': '陳雅婷 推薦了新朋友 +2,000積分',
      'about.liveActivity.member5': '劉志強 完成了風險評估測試 +800積分',
      'about.liveActivity.member6': '黃小芳 參加了退休規劃工作坊 +1,200積分',
      'about.testimonials.title': '會員心聲',
      'about.testimonials.subtitle': '聽聽我們的會員怎麼說',
      'about.testimonials.testimonial1.name': '張小明',
      'about.testimonials.testimonial1.role': '工程師',
      'about.testimonials.testimonial1.text': '透過積分系統，我不僅學到了理財知識，還換到了心儀的禮品！',
      'about.testimonials.testimonial2.name': '李美玲',
      'about.testimonials.testimonial2.role': '教師',
      'about.testimonials.testimonial2.text': '團隊非常專業且親切，讓我對財務規劃有了全新的認識。',
      'about.testimonials.testimonial3.name': '王建國',
      'about.testimonials.testimonial3.role': '創業者',
      'about.testimonials.testimonial3.text': '活動很有趣，認識了很多志同道合的朋友，還賺到了積分！',

      // Roles
      'roles.super_admin.emoji': '👑',
      'roles.admin.emoji': '👑',
      'roles.agent.emoji': '👨‍💼',
      'roles.client.emoji': '👤',


      // Common
      'common.retry': '重試',
      'common.loading': '載入中...',
      'common.error': '錯誤',
      'common.success': '成功',
      'common.cancel': '取消',
      'common.save': '保存',
      'common.delete': '刪除',
      'common.edit': '編輯',
      'common.add': '添加',
      'common.remove': '移除',
      'common.close': '關閉',
      'common.back': '返回',
      'common.next': '下一步',
      'common.previous': '上一步',
      'common.submit': '提交',
      'common.confirm': '確認',
      'common.yes': '是',
      'common.no': '否',

      // Register
      'register.title': '註冊',
      'register.haveAccount': '已有帳戶？',
      'register.login': '登入',
      'register.firstName': '名字',
      'register.lastName': '姓氏',
      'register.email': '電子郵件',
      'register.role': '角色',
      'register.client': '客戶',
      'register.agent': '代理',
      'register.password': '密碼',
      'register.confirmPassword': '確認密碼',
      'register.terms': '我同意服務條款和隱私政策',
      'register.submit': '註冊',
      'register.or': '或',
      'register.google': '使用 Google 註冊',
      'register.facebook': '使用 Facebook 註冊',

      // Dashboard
      'dashboard.error': '載入儀表板時發生錯誤',
      'dashboard.noData': '沒有可用的數據',
      'dashboard.unknownRole': '未知角色',

      // Help Center
      'help.title': '幫助中心',
      'help.subtitle': '我們在這裡幫助您',
      'help.faq': '常見問題',
      'help.contactSupport': '聯繫支持',
      'help.legal': '法律條款',
      'help.getStarted': '如何開始使用平台？',
      'help.getStartedAnswer': '註冊帳戶，選擇您的角色，然後開始探索我們的功能。',
      'help.aiContent': 'AI 內容生成器如何工作？',
      'help.aiContentAnswer': '輸入您的需求，AI 將為您生成相關內容。',
      'help.agentCost': '代理服務的費用是多少？',
      'help.agentCostAnswer': '費用因代理和服務而異，請聯繫具體代理了解詳情。',
      'help.contests': '如何參加競賽？',
      'help.contestsAnswer': '瀏覽競賽頁面，選擇您感興趣的競賽並提交作品。',
      'help.security': '我的數據安全嗎？',
      'help.securityAnswer': '我們使用最新的安全技術保護您的數據。',
      'help.support': '如何獲得支持？',
      'help.supportAnswer': '您可以通過電子郵件、電話或即時聊天聯繫我們。',
      'help.emailSupport': '電子郵件支持',
      'help.responseTime': '24小時內回覆',
      'help.phoneSupport': '電話支持',
      'help.workingHours': '工作時間：週一至週五 9AM-6PM',
      'help.liveChat': '即時聊天',
      'help.instantResponse': '即時回覆',
      'help.clickToStartChat': '點擊開始聊天',

      // AI Trial
      'aiTrial.title': 'AI 內容生成器',
      'aiTrial.subtitle': '使用 AI 生成高質量內容',
      'aiTrial.industry': '行業',
      'aiTrial.contentType': '內容類型',
      'aiTrial.generateButton': '生成內容',
      'aiTrial.result': '生成結果',
      'aiTrial.copy': '複製',
      'aiTrial.download': '下載',

      // Contest
      'contest.title': '創意競賽',
      'contest.current': '當前競賽',
      'contest.pastWinners': '過往獲獎者',
      'contest.deadline': '截止日期',
      'contest.prizeInfo': '獎品信息',
      'contest.financialChallenge': '財務挑戰',
      'contest.challengeDescription': '創建引人入勝的財務內容',
      'contest.firstPlace': '第一名',
      'contest.secondPlace': '第二名',
      'contest.thirdPlace': '第三名',
      'contest.featuredOnPlatform': '平台推薦',
      'contest.recognitionBadge': '認可徽章',
      'contest.premiumMembership': '高級會員',
      'contest.category.social_media': '社交媒體',
      'contest.category.blog_article': '博客文章',
      'contest.category.infographic': '信息圖表',
      'contest.category.video_content': '視頻內容',
      'contest.category.email_campaign': '電子郵件營銷',
      'contest.category.podcast_script': '播客腳本',
      'contest.rule1': '原創內容',
      'contest.rule2': '符合主題',
      'contest.rule3': '高質量標準',
      'contest.rule4': '按時提交',
      'contest.rule5': '遵守規則',

      // Footer
      'footer.about': '關於我們',
      'footer.privacy': '隱私政策',
      'footer.terms': '服務條款',
      'footer.copyright': '版權所有',

      'financialPlanning.retirementPeriod': '退休期',
      'financialPlanning.longTerm': '長期',
      'financialPlanning.workingPeriod': '工作期',
    },
    'en': {
      // Lifestyle Options
      'lifestyle.active': 'Active Lifestyle',
      'lifestyle.family': 'Family Oriented',
      'lifestyle.traveler': 'Traveler',
      'lifestyle.foodie': 'Foodie',
      'lifestyle.creative': 'Creative',
      'lifestyle.tech': 'Tech Enthusiast',
      'lifestyle.wellness': 'Wellness Focused',
      'lifestyle.finance': 'Finance Savvy',
      'lifestyle.student': 'Student',
      'lifestyle.retiree': 'Retiree',

      // Events Page
      'events.title': 'Latest Events',
      'events.description': 'Explore our events, connect with professionals, and gain the latest financial knowledge',
      'events.upcoming': 'Upcoming',
      'events.past': 'Past Events',
      'events.noUpcoming': 'No upcoming events',
      'events.noPast': 'No past events',
      'events.checkBackLater': 'Please check back later for new events',
      'events.noPastEvents': 'No past events available',
      'events.registered': 'registered',
      'events.register': 'Register Now',
      'events.cancelRegistration': 'Cancel Registration',
      'events.loginToRegister': 'Login to Register',
      'events.details': 'Event Details',
      'events.dateAndTime': 'Date and Time',
      'events.locationAndCapacity': 'Location and Capacity',
      'events.pricingAndRewards': 'Pricing and Rewards',
      'events.price': 'Price',
      'events.free': 'Free',
      'events.pointsReward': 'Points Reward',
      'events.points': 'Points',
      'events.participants': 'Participants',
      
      // Event Types
      'events.workshop': 'Workshop',
      'events.seminar': 'Seminar',
      'events.consultation': 'Consultation',
      'events.webinar': 'Webinar',
      
      // Homepage - Events
      'events.financialPlanning': 'Financial Planning Workshop',
      'events.investmentStrategy': 'Investment Strategy Seminar',
      'events.retirementPlanning': 'Retirement Planning Masterclass',
      'events.revisit': 'Revisit',
      'events.viewAll': 'View All Events',

      // Homepage - Partners
      'partners.title': 'Partners',

      // Homepage - Blogs
      'blogs.title': 'Market News',
      'blogs.investmentStrategies2024': 'Investment Strategies for 2024',
      'blogs.investmentStrategiesExcerpt': 'Explore the latest investment trends and opportunities for 2024 to make informed investment decisions.',
      'blogs.insurancePolicies': 'Understanding Insurance Policies',
      'blogs.insurancePoliciesExcerpt': 'Deep dive into various insurance products to help you choose the right coverage.',
      'blogs.retirementEssentials': 'Retirement Planning Essentials',
      'blogs.retirementEssentialsExcerpt': 'Master the key elements of retirement planning to ensure a worry-free retirement.',
      'blogs.readMore': 'Read More',
      'blogs.viewAll': 'View All Blogs',

      // Homepage - Become a Member
      'member.title': 'Become a Member',
      'member.subtitle': 'Join now and get 1,000 points free',
      'member.cta': 'Register Now',

      // Homepage - Hero Section
      'home.hero.registerNow': 'Reserve your seat NOW',
      
      // Homepage - About Section
      'home.about.title': 'What is Persona Centric?',
      'home.about.subtitle': 'Events, Rewards, Friends, Knowledge',
      'home.about.benefit1.title': 'Financial Partner Matching',
      'home.about.benefit1.desc': 'AI technology matches you with the perfect financial advisor',
      'home.about.benefit2.title': 'Events',
      'home.about.benefit2.desc': 'Join events, make new friends, win prizes',
      'home.about.benefit3.title': 'Points Game',
      'home.about.benefit3.desc': 'Earn points and rewards by participating in platform activities',
      'home.about.benefit4.title': 'Knowledge Base',
      'home.about.benefit4.desc': 'latest financial knowledge and investment strategies',
      'home.gifts.title': 'Quizzes',
      'home.gifts.subtitle': 'Get free gifts! (This month\'s grand prize: iPhone16)',
      'home.gifts.cta': 'Register now and get 10000 points',
      'home.match.title': '5 Questions',
      'home.match.subtitle': 'to Match with your perfect Financial planner',
      'home.match.cta': 'Match Now',
      'home.events.title': 'Events',
      'home.events.cta': 'Join Now',
      'home.hero.title': 'Food for Talk',
      'home.hero.eventDate': 'October 2025',
      'home.gifts.description': 'Complete quizzes and win prizes',
      'home.gifts.participate': 'Join Now',
      'home.events.description': 'Join our events, make friends and more',
      'partners.placeholder': 'Partner {number}',

      // Homepage - Small CTA
      'home.getRightAgent': 'AI technology matches you with the perfect financial advisor',
      'smallCTA.button': 'Get Started',

      // Homepage - Stats
      'home.proofOfConcept': 'Proof of Concept',
      'home.realResults': 'Our platform\'s real results',
      'stats.agents': 'Agents',
      'stats.clients': 'Successful Clients',
      'stats.growth': 'Investment Growth',
      'stats.activeAdvisors': 'Active financial advisors',
      'stats.successfulClients': 'Successful clients served',
      'stats.averageGrowth': 'Average investment growth',

      // Contest Winners
      'contest.winners.socialMedia': 'Social Media Post',
      'contest.winners.blogArticle': 'Blog Article',
      'contest.winners.posterDesign': 'Poster Design',
      'contest.winners.videoContent': 'Video Content',
      'contest.winners.bestViralPost': 'Best viral post about financial literacy',
      'contest.winners.insightfulBlog': 'Insightful blog on investment strategies',
      'contest.winners.creativePoster': 'Creative poster for retirement planning',
      'contest.winners.engagingVideo': 'Engaging video on insurance basics',

      // Financial Planning - Main
      'financialPlanning.title': 'Financial Product Planning',
      'financialPlanning.tab': 'Financial Planning',
      'financialPlanning.page1': 'Product Configuration',
      'financialPlanning.page2': 'Financial Analysis',
      'financialPlanning.create': 'Create',
      'financialPlanning.loadSaved': 'Load Saved',
      'financialPlanning.save': 'Save',
      'financialPlanning.cancel': 'Cancel',
      'financialPlanning.close': 'Close',
      'financialPlanning.back': 'Back',
      'financialPlanning.next': 'Next',
      'financialPlanning.previous': 'Previous',
      'financialPlanning.load': 'Load',

      // Product Categories
      'financialPlanning.selectCategory': 'Select Product Category',
      'financialPlanning.investment': 'Investment',
      'financialPlanning.saving': 'Saving',
      'financialPlanning.realEstate': 'Real Estate',
      'financialPlanning.selectProduct': 'Select Product Type',
      'financialPlanning.funds': 'Funds',
      'financialPlanning.mpf': 'MPF',
      'financialPlanning.savingPlans': 'Saving Plans',
      'financialPlanning.bank': 'Bank',
      'financialPlanning.annuity': 'Annuity',
      'financialPlanning.ownLiving': 'Own Living',
      'financialPlanning.rental': 'Rental',

      // Product Management
      'financialPlanning.product': 'Product',
      'financialPlanning.addProduct': 'Add Product',
      'financialPlanning.removeProduct': 'Remove Product',
      'financialPlanning.duplicateProduct': 'Duplicate Product',
      'financialPlanning.noProducts': 'No products added yet',
      'financialPlanning.noProductsDescription': 'Click "Create" to start adding financial products',

      // User Management
      'financialPlanning.loadUser': 'Load User',
      'financialPlanning.noSavedUsers': 'No saved users',
      'financialPlanning.noSavedUsersDescription': 'Please create and save user financial product configurations first',

      // Financial Analysis
      'financialPlanning.financialAnalysis': 'Financial Analysis Settings',
      'financialPlanning.retirementAge': 'Retirement Age',
      'financialPlanning.inflationRate': 'Inflation Rate (%)',
      'financialPlanning.currentAssets': 'Current Assets (HKD)',
      'financialPlanning.analysisPeriod': 'Analysis Period',
      'financialPlanning.to': 'to',
      'financialPlanning.recalculate': 'Recalculate',
      'financialPlanning.calculating': 'Calculating...',
      'financialPlanning.startAnalysis': 'Start Financial Analysis',
      'financialPlanning.startAnalysisDescription': 'Set your financial parameters and click "Recalculate" to start analysis',
      'financialPlanning.startAnalysisButton': 'Start Analysis',

      // Expenses
      'financialPlanning.expenses': 'Expense Settings',
      'financialPlanning.addExpenseStage': 'Add Expense Stage',
      'financialPlanning.ageFrom': 'Age From',
      'financialPlanning.ageTo': 'Age To',
      'financialPlanning.monthlyExpenses': 'Monthly Expenses',
      'financialPlanning.removeExpense': 'Remove Expense',

      // Results Table
      'financialPlanning.annualFinancialStatus': 'Annual Financial Status',
      'financialPlanning.age': 'Age',
      'financialPlanning.totalMonthlyIncome': 'Total Monthly Income',
      'financialPlanning.passiveIncome': 'Passive Income',
      'financialPlanning.totalExpenses': 'Monthly Expenses',
      'financialPlanning.netCashFlow': 'Net Cash Flow',
      'financialPlanning.totalAssets': 'Total Assets',
      'financialPlanning.totalLiabilities': 'Total Liabilities',
      'financialPlanning.netWorth': 'Net Worth',
      'financialPlanning.accumulatedFlexibleFunds': 'Annual Flexible Funds',

      // Charts
      'financialPlanning.financialTrendChart': 'Financial Trend Chart',
      'financialPlanning.assetAllocation': 'Asset Allocation',
      'financialPlanning.incomeSourcesAnalysis': 'Income Sources Analysis',
      'financialPlanning.selectAge': 'Select Age',
      'financialPlanning.yearsOld': 'years old',
      'financialPlanning.property': 'Property',
      'financialPlanning.cash': 'Cash',
      'financialPlanning.investments': 'Investments',
      'financialPlanning.other': 'Other',
      'financialPlanning.flexibleFunds': 'Annual Flexible Funds',
      'financialPlanning.workIncome': 'Work Income',
      'financialPlanning.investmentIncome': 'Investment Income',
      'financialPlanning.fundIncome': 'Fund Income',
      'financialPlanning.mpfIncome': 'MPF Income',
      'financialPlanning.savingIncome': 'Saving Income',
      'financialPlanning.bankIncome': 'Bank Interest',
      'financialPlanning.bankReturn': 'Bank Return',
      'financialPlanning.annuityIncome': 'Annuity Income',
      'financialPlanning.rentalIncome': 'Rental Income',
      'financialPlanning.incomeSources': 'Income Sources (HKD)',
      'financialPlanning.annualIncomeSources': 'Annual Income Sources',
      'financialPlanning.netWorthPassiveIncomeExpenses': 'Net Worth, Passive Income & Expenses Trend',

      // Formula Info
      'financialPlanning.viewChartExplanation': 'View Chart Explanation',
      'financialPlanning.viewCalculationFormula': 'View Calculation Formula',
      'financialPlanning.formulaExplanation': 'Calculation Formula:',
      'financialPlanning.description': 'Description:',
      'financialPlanning.unknown': 'Unknown',
      'financialPlanning.noFormula': 'No Formula',
      'financialPlanning.noDescription': 'No Description',

      // PDF Report
      'financialPlanning.pdfReport': 'PDF Report',
      'financialPlanning.client': 'Client',
      'financialPlanning.downloadPDF': 'Download PDF',
      'financialPlanning.financialPlanningReport': 'Financial Product Planning Report',
      'financialPlanning.preparedFor': 'Prepared for',
      'financialPlanning.reportDate': 'Report Date',
      'financialPlanning.executiveSummary': 'Executive Summary',
      'financialPlanning.configuredProducts': 'Configured Products',
      'financialPlanning.productConfiguration': 'Product Configuration',
      'financialPlanning.productType': 'Product Type',
      'financialPlanning.details': 'Details',
      'financialPlanning.projectedValue': 'Projected Value',
      'financialPlanning.investmentAmount': 'Investment Amount',
      'financialPlanning.expectedReturn': 'Expected Return',
      'financialPlanning.monthlySalary': 'Monthly Salary',
      'financialPlanning.contribution': 'Contribution',
      'financialPlanning.monthly': 'Monthly',
      'financialPlanning.interestRate': 'Interest Rate',
      'financialPlanning.purchasePrice': 'Purchase Price',
      'financialPlanning.rentalExpenses': 'Rental Expenses',
      'financialPlanning.rentAmount': 'Rent Amount',
      'financialPlanning.noDetails': 'No Details',
      'financialPlanning.recommendations': 'Recommendations',
      'financialPlanning.recommendation1': 'Regularly review and adjust your investment portfolio to align with market changes',
      'financialPlanning.recommendation2': 'Consider increasing retirement savings to ensure quality of life after retirement',
      'financialPlanning.recommendation3': 'Diversify investments to spread risk and increase return potential',
      'financialPlanning.recommendation4': 'Regularly meet with financial advisors to review and optimize your financial plan',
      'financialPlanning.reportFooter1': 'This report is for reference only and does not constitute investment advice',
      'financialPlanning.reportFooter2': 'Please consult a professional financial advisor for personalized investment advice',
      'financialPlanning.chartPlaceholder': 'Chart Placeholder',
      'financialPlanning.clientName': 'Client Name',
      'financialPlanning.enterClientName': 'Enter client name',
      'financialPlanning.generateReport': 'Generate Report',
      'financialPlanning.reportGenerated': 'Report generated successfully',
      'financialPlanning.reportGenerationFailed': 'Report generation failed',

      // Recommendations Editor
      'financialPlanning.editRecommendations': 'Edit Recommendations',
      'financialPlanning.resetToDefault': 'Reset to Default',
      'financialPlanning.recommendationsDescription': 'Customize your financial planning recommendations. These recommendations will appear in the PDF report to provide professional financial guidance to clients.',
      'financialPlanning.enterRecommendation': 'Enter recommendation content...',
      'financialPlanning.removeRecommendation': 'Remove Recommendation',
      'financialPlanning.addRecommendation': 'Add Recommendation',
      'financialPlanning.recommendationsPreview': 'Recommendations Preview',
      'financialPlanning.emptyRecommendation': '(Empty recommendation)',
      'financialPlanning.editRecommendationsButton': 'Edit Recommendations',

      // Report Generation Section
      'financialPlanning.reportGeneration': 'Report Generation',
      'financialPlanning.reportGenerationDescription': 'Generate a professional PDF report containing all financial planning data. Please ensure all required information is completed.',
      'financialPlanning.completed': 'Completed',
      'financialPlanning.required': 'Required',
      'financialPlanning.products': 'Product Configuration',

      // Product Card Fields - Funds
      'productCard.fundAllocation': 'Fund Allocation',
      'productCard.growth': 'Growth',
      'productCard.dividends': 'Dividends',
      'productCard.investmentAmount': 'Investment Amount (HKD)',
      'productCard.startAge': 'Start Age',
      'productCard.expectedReturn': 'Expected Annual Return (%)',
      'productCard.expectedReturnPlaceholder': 'e.g., 8 means 8% annual return',
      'productCard.expectedWithdrawalAge': 'Expected Withdrawal Age',
      'productCard.expectedWithdrawalAgePlaceholder': 'e.g., 65 means withdraw at age 65',
      'productCard.fundCategory': 'Fund Category',
      'productCard.growthFund': 'Growth Fund',
      'productCard.dividendFund': 'Dividend Fund',
      'productCard.monthlyDividends': 'Monthly Dividends',
      'productCard.yearlyDividends': 'Yearly Accumulated Dividends',
      'productCard.totalDividends': 'Total Dividends Until Withdrawal Age',
      'productCard.totalReturn': 'Total Return at Surrender',
      'productCard.compoundCalculation': 'Compound Calculation',
      'productCard.simpleCalculation': 'Simple Calculation',

      // Product Card Fields - MPF
      'productCard.monthlySalary': 'Monthly Salary (HKD)',
      'productCard.salaryIncrement': 'Annual Salary Increment (%)',
      'productCard.employerContribution': 'Employer Contribution (%)',
      'productCard.employeeContribution': 'Employee Contribution (%)',
      'productCard.currentAge': 'Current Age',
      'productCard.currentMPFAmount': 'Current MPF Amount',
      'productCard.mpfAt65': 'MPF Total at Age 65',
      'productCard.totalDividendsEarned': 'Total Dividends Earned',
      'productCard.mpfWithoutDividends': 'MPF Value Without Dividends',
      'productCard.employeeContributionDeduction': 'Employee Contribution Deduction',

      // Product Card Fields - Saving Plans
      'productCard.planName': 'Plan Name',
      'productCard.contribution': 'Contribution Amount',
      'productCard.contributionType': 'Contribution Frequency',
      'productCard.monthly': 'Monthly',
      'productCard.yearly': 'Yearly',
      'productCard.contributionDuration': 'Contribution Duration',
      'productCard.surrenderAge': 'Surrender Age',
      'productCard.planType': 'Plan Type',
      'productCard.duration': 'Duration',
      'productCard.interestRate': 'Interest Rate (%)',
      'productCard.withdrawalAge': 'Withdrawal Age',
      'productCard.contributionAmount': 'Contribution Amount',
      'productCard.frequency': 'Frequency',
      'productCard.startDate': 'Start Date',
      'productCard.targetRetirementAge': 'Target Retirement Age',
      'productCard.expectedAnnualReturn': 'Expected Annual Return (%)',
      'productCard.breakEvenPeriod': 'Break-even Period (Years)',
      'productCard.withdrawalAmount': 'Withdrawal Amount',
      'productCard.withdrawalPeriod': 'Withdrawal Period',
      'productCard.surrenderValue': 'Surrender Value',
      'productCard.contributionPeriod': 'Contribution Period',

      // Product Card Fields - Bank
      'productCard.saving': 'Saving (Flexible Funds)',
      'productCard.fixedDeposit': 'Fixed Deposit',
      'productCard.existingAmount': 'Existing Amount',
      'productCard.contributionFrequency': 'Contribution Frequency',
      'productCard.alreadyOwned': 'Already Owned',
      'productCard.yes': 'Yes',
      'productCard.no': 'No',
      'productCard.lockInPeriod': 'Lock-in Period (Months)',
      'productCard.totalSavings': 'Total Savings Amount',
      'productCard.totalAmount': 'Total Amount',

      // Product Card Fields - Own Living
      'productCard.purchasePrice': 'Purchase Price (HKD)',
      'productCard.downPayment': 'Down Payment (%)',
      'productCard.downPaymentPlaceholder': 'e.g., 30',
      'productCard.mortgageStartAge': 'Mortgage Start Age',
      'productCard.currentSituation': 'Current Situation',
      'productCard.selfOccupied': 'Self Occupied',
      'productCard.renting': 'Renting',
      'productCard.monthlyRent': 'Monthly Rent (HKD)',
      'productCard.rentStartAge': 'Rent Start Age',
      'productCard.rentIncreaseRate': 'Rent Increase Rate (%)',
      'productCard.monthlyPayment': 'Monthly Payment',
      'productCard.sellAge': 'Sell Age',
      'productCard.willNotSell': 'Will Not Sell',
      'productCard.willSell': 'Will Sell',
      'productCard.sellAgePlaceholder': 'e.g., 65',
      'productCard.mortgageInterestRate': 'Mortgage Interest Rate (%)',
      'productCard.mortgageInterestRatePlaceholder': 'e.g., 3.5',
      'productCard.mortgageCompletionAge': 'Mortgage Completion Age',
      'productCard.mortgageCompletionAgePlaceholder': 'e.g., 60',
      'productCard.totalInterestPaid': 'Total Interest Paid',
      'productCard.propertyValueAtCompletion': 'Property Value at Completion',
      'productCard.propertyValueGrowth': 'Property Value Growth (%)',
      'productCard.propertyValueGrowthPlaceholder': 'e.g., 1.0',
      'productCard.propertyValueAtAge': 'Property Value at Age {age}',
      'productCard.saleProceeds': 'Sale Proceeds',

      // Product Card Fields - Rental
      'productCard.monthlyRentExpense': 'Monthly Rent Expense',
      'productCard.leaseStartAge': 'Lease Start Age',
      'productCard.rentIncreaseRatePlaceholder': 'e.g., 3',
      'productCard.expectedEndAge': 'Expected End Age',
      'productCard.totalRentPaid': 'Total Rent Paid',

      // Product Card Fields - Annuity
      'productCard.annuityType': 'Annuity Type',
      'productCard.deferred': 'Deferred',
      'productCard.immediate': 'Immediate',
      'productCard.annualContribution': 'Annual Contribution (HKD)',
      'productCard.annualContributionPlaceholder': 'e.g., 100000',
      'productCard.contributionAmountPlaceholder': 'e.g., 1000000',
      'productCard.gender': 'Gender',
      'productCard.male': 'Male',
      'productCard.female': 'Female',
      'productCard.annuityStartAge': 'Annuity Start Age',
      'productCard.premiumAge': 'Premium Age',
      'productCard.lifeExpectancy': 'Life Expectancy',
      'productCard.monthlyAnnuity': 'Monthly Annuity',
      'productCard.totalAnnuityIncome': 'Total Annuity Income',
      'productCard.internalRateOfReturn': 'Internal Rate of Return',

      // Product Card - Common
      'productCard.removeProduct': 'Remove Product',
      'productCard.duplicateProduct': 'Duplicate Product',
      'productCard.summary': 'Summary',
      'productCard.unknownProductType': 'Unknown Product Type',
      'productCard.productNumber': 'Product #',
      'productCard.copyProduct': 'Copy Product',
      'productCard.deleteProduct': 'Delete Product',

      // Info Dialog
      'productCard.viewFormula': 'View Calculation Formula',
      'productCard.calculationFormula': 'Calculation Formula',
      'productCard.explanation': 'Explanation',

      // Dashboard
      'dashboard.tabs.overview': 'Overview',
      'dashboard.tabs.agentConnection': 'Agent Connection',
      'dashboard.tabs.events': 'Events',
      'dashboard.tabs.blogManagement': 'Blog Management',
      'dashboard.tabs.points': 'Points',
      'dashboard.tabs.contests': 'Contests',
      'dashboard.tabs.profile': 'Profile',
      'dashboard.tabs.financial_planning': 'Financial Planning',

      // Navigation
      'nav.events': 'Events',
      'nav.agentPairing': 'Agent Pairing',
      'nav.contentGenerator': 'Content Generator',
      'nav.blogs': 'Blogs',
      'nav.about': 'About Us',
      'nav.login': 'Login',
      'nav.register': 'Register',

      // Actions
      'actions.allAgents': 'All Agents',
      'actions.dashboard': 'Dashboard',
      'actions.logout': 'Logout',

      // Agent Matching
      'matching.title': 'Smart Client Matching System',
      'matching.subtitle': 'Answer a few simple questions and we\'ll find the perfect financial advisor for you',
      'matching.previous': 'Previous',
      'matching.next': 'Next',
      'matching.finish': 'Complete Matching',
      'matching.retake': 'Retake Quiz',
      'matching.viewAllAgents': 'View All Agents',
      'matching.yourPerfectMatches': 'Your Perfect Matches',
      'matching.basedOnAnswers': 'Based on your answers, here are the advisors best suited to help you achieve your financial goals.',
      'matching.matching': 'Matching...',
      'matching.match': 'Match',
      'matching.matchHighlights': 'Match Highlights',
      'matching.contactNow': 'Contact Now',
      'matching.viewFullProfile': 'View Full Profile',
      'matching.whyUseOurSystem': 'Why Use Our Matching System?',
      'matching.preciseMatching': 'Precise Matching',
      'matching.preciseMatchingDesc': 'AI-powered algorithm finds advisors who match your specific needs and preferences',
      'matching.saveTime': 'Save Time',
      'matching.saveTimeDesc': 'Skip the research and get matched with qualified advisors in minutes',
      'matching.verifiedAdvisors': 'Verified Advisors',
      'matching.verifiedAdvisorsDesc': 'All advisors are verified professionals with proven track records',

      // About Us
      'about.title': 'About Persona Centric',
      'about.subtitle': 'Redefining the Future of Financial Planning',
      'about.hero.title': 'Your Perfect Financial Advisor',
      'about.hero.subtitle': 'Intelligent matching, event experiences and reward systems, achieve your financial goals',
      'about.hero.cta': 'Become a Member Now',
      'about.hero.learnMore': 'Learn More',
      'about.mission.title': 'Mission',
      'about.mission.subtitle': 'Help everyone find their perfect financial advisor and build long-term trust relationships',
      'about.mission.description': 'We believe financial planning should not be a one-size-fits-all service. Everyone\'s financial situation, goals, and risk tolerance are different, requiring personalized advice and ongoing support.',
      'about.coreValues.title': 'Core Values',
      'about.coreValues.personalized': 'Personalized Matching',
      'about.coreValues.personalizedDesc': 'AI-driven matching system that finds the perfect financial advisor based on your specific needs and preferences',
      'about.coreValues.trust': 'Building Trust',
      'about.coreValues.trustDesc': 'Build deep trust relationships with advisors through events and face-to-face interactions',
      'about.coreValues.engagement': 'Continuous Engagement',
      'about.coreValues.engagementDesc': 'Points system and reward mechanisms makes financial planning fun',
      'about.coreValues.transparency': 'Transparent Management',
      'about.coreValues.transparencyDesc': 'One-stop dashboard that gives you clear visibility into all your investments and recommendations',
      'about.features.title': 'Platform Features',
      'about.features.matching.title': 'Intelligent Advisor Matching',
      'about.features.matching.desc': 'Answer simple questions and we\'ll find the perfect financial advisor for you',
      'about.features.events.title': 'Real Event Experiences',
      'about.features.events.desc': 'Participate in various financial events and get to know your advisor in a relaxed environment',
      'about.features.points.title': 'Points Reward System',
      'about.features.points.desc': 'Complete questionnaires, attend events, and earn points to redeem gift vouchers and rewards',
      'about.features.dashboard.title': 'One-Stop Dashboard',
      'about.features.dashboard.desc': 'All investments at a glance with regular updates and professional recommendations',
      'about.howItWorks.title': 'How It Works',
      'about.howItWorks.step1.title': 'Register as Member',
      'about.howItWorks.step1.desc': 'Simple registration with immediate 10,000 points bonus',
      'about.howItWorks.step2.title': 'Complete Matching Quiz',
      'about.howItWorks.step2.desc': 'Answer questions to find your perfect financial advisor',
      'about.howItWorks.step3.title': 'Attend Events & Build Relationships',
      'about.howItWorks.step3.desc': 'Get to know your advisor through events and build trust',
      'about.howItWorks.step4.title': 'Start Financial Planning',
      'about.howItWorks.step4.desc': 'Receive personalized advice and track investment progress',
      'about.benefits.title': 'Member Benefits',
      'about.benefits.personalized.title': 'Personalized Financial Advice',
      'about.benefits.personalized.desc': 'Receive tailored financial planning advice based on your specific circumstances',
      'about.benefits.exclusive.title': 'Exclusive Event Priority',
      'about.benefits.exclusive.desc': 'Priority access to various financial education events and seminars',
      'about.benefits.rewards.title': 'Rich Reward System',
      'about.benefits.rewards.desc': 'Complete tasks to earn points and redeem various practical gifts and services',
      'about.benefits.support.title': 'Professional Ongoing Support',
      'about.benefits.support.desc': 'Receive continuous financial advice and portfolio updates',
      'about.stats.title': 'Platform Statistics',
      'about.stats.advisors': 'Professional Advisors',
      'about.stats.members': 'Active Members',
      'about.stats.events': 'Successful Events',
      'about.stats.satisfaction': 'Satisfaction Rate',
      'about.cta.title': 'Ready to Start Your Financial Planning Journey?',
      'about.cta.subtitle': 'Join us to find your perfect financial advisor and achieve financial freedom',
      'about.cta.register': 'Register Now',
      'about.cta.learnMore': 'Learn More',
      'about.team.title': 'About Our Team',
      'about.team.subtitle': 'Passionate professionals dedicated to providing you with the best financial planning services',
      'about.team.member1.name': 'Zhang Xiaoming',
      'about.team.member1.role': 'Founder & CEO',
      'about.team.member1.bio': 'With 15 years of experience in financial technology, he is dedicated to making financial planning more accessible',
      'about.team.member2.name': 'Li Meiling',
      'about.team.member2.role': 'Chief Technology Officer',
      'about.team.member2.bio': 'AI expert, responsible for developing and optimizing the matching system',
      'about.team.member3.name': 'Wang Jianguo',
      'about.team.member3.role': 'Operations Director',
      'about.team.member3.bio': 'Event planner expert, creating unforgettable experiences for members',
      'about.team.member4.name': 'Chen Yating',
      'about.team.member4.role': 'Customer Success Manager',
      'about.team.member4.bio': 'Ensuring that every member receives the best service experience',
      'about.giftSystem.title': '🎁 Points Reward System',
      'about.giftSystem.subtitle': 'The more you participate, the more rewards you get!',
      'about.giftSystem.signup.title': 'Sign Up Now',
      'about.giftSystem.signup.points': '10,000 points',
      'about.giftSystem.signup.desc': 'New members get a generous points bonus upon registration',
      'about.giftSystem.earn.title': 'Earn Points',
      'about.giftSystem.earn.quiz': 'Complete survey',
      'about.giftSystem.earn.event': 'Participate in events',
      'about.giftSystem.earn.referral': 'Refer friends',
      'about.giftSystem.earn.points': '500-2,000 points',
      'about.giftSystem.redeem.title': 'Redeem Gifts',
      'about.giftSystem.redeem.desc': 'Redeem various beautiful gifts and gift cards with points',
      'about.giftSystem.featured.title': 'Popular Gifts',
      'about.giftSystem.featured.airpods': 'Apple AirPods Pro',
      'about.giftSystem.featured.coffee': 'High-end coffee machine',
      'about.giftSystem.featured.giftcard': 'HKD50 Event Gift Card',
      'about.giftSystem.cta': 'View Gift Catalog',
      'about.liveActivity.title': '🔥 Live Activity',
      'about.liveActivity.subtitle': 'See what our members are doing',
      'about.liveActivity.member1': 'Zhang Xiaoming just completed the financial health questionnaire +500 points',
      'about.liveActivity.member2': 'Li Meiling attended the investment and financial literacy seminar +1,000 points',
      'about.liveActivity.member3': 'Wang Jianguo redeemed Apple AirPods Pro -5,000 points',
      'about.liveActivity.member4': 'Chen Yating recommended new friends +2,000 points',
      'about.liveActivity.member5': 'Liu Zhiqiang completed the risk assessment test +800 points',
      'about.liveActivity.member6': 'Huang Xiaofang attended the retirement planning workshop +1,200 points',
      'about.testimonials.title': 'Member Voices',
      'about.testimonials.subtitle': 'Hear what our members have to say',
      'about.testimonials.testimonial1.name': 'Zhang Xiaoming',
      'about.testimonials.testimonial1.role': 'Engineer',
      'about.testimonials.testimonial1.text': 'Through the points system, I not only learned about financial knowledge, but also exchanged for the gift I wanted!',
      'about.testimonials.testimonial2.name': 'Li Meiling',
      'about.testimonials.testimonial2.role': 'Teacher',
      'about.testimonials.testimonial2.text': 'The team is very professional and friendly, giving me a whole new perspective on financial planning.',
      'about.testimonials.testimonial3.name': 'Wang Jianguo',
      'about.testimonials.testimonial3.role': 'Entrepreneur',
      'about.testimonials.testimonial3.text': 'The activities are very interesting, and I made new friends and earned points!',

      // Roles
      'roles.super_admin.emoji': '👑',
      'roles.admin.emoji': '👑',
      'roles.agent.emoji': '👨‍💼',
      'roles.client.emoji': '👤',


      // Common
      'common.retry': 'Retry',
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'common.delete': 'Delete',
      'common.edit': 'Edit',
      'common.add': 'Add',
      'common.remove': 'Remove',
      'common.close': 'Close',
      'common.back': 'Back',
      'common.next': 'Next',
      'common.previous': 'Previous',
      'common.submit': 'Submit',
      'common.confirm': 'Confirm',
      'common.yes': 'Yes',
      'common.no': 'No',

      // Register
      'register.title': 'Register',
      'register.haveAccount': 'Already have an account?',
      'register.login': 'Login',
      'register.firstName': 'First Name',
      'register.lastName': 'Last Name',
      'register.email': 'Email',
      'register.role': 'Role',
      'register.client': 'Client',
      'register.agent': 'Agent',
      'register.password': 'Password',
      'register.confirmPassword': 'Confirm Password',
      'register.terms': 'I agree to the Terms of Service and Privacy Policy',
      'register.submit': 'Register',
      'register.or': 'or',
      'register.google': 'Register with Google',
      'register.facebook': 'Register with Facebook',

      // Dashboard
      'dashboard.error': 'Error loading dashboard',
      'dashboard.noData': 'No data available',
      'dashboard.unknownRole': 'Unknown role',

      // Help Center
      'help.title': 'Help Center',
      'help.subtitle': 'We are here to help',
      'help.faq': 'Frequently Asked Questions',
      'help.contactSupport': 'Contact Support',
      'help.legal': 'Legal',
      'help.getStarted': 'How do I get started with the platform?',
      'help.getStartedAnswer': 'Register an account, choose your role, and start exploring our features.',
      'help.aiContent': 'How does the AI content generator work?',
      'help.aiContentAnswer': 'Enter your requirements and AI will generate relevant content for you.',
      'help.agentCost': 'How much do agent services cost?',
      'help.agentCostAnswer': 'Costs vary by agent and service, please contact specific agents for details.',
      'help.contests': 'How do I participate in contests?',
      'help.contestsAnswer': 'Browse the contests page, choose a contest you are interested in and submit your work.',
      'help.security': 'Is my data secure?',
      'help.securityAnswer': 'We use the latest security technology to protect your data.',
      'help.support': 'How do I get support?',
      'help.supportAnswer': 'You can contact us via email, phone or live chat.',
      'help.emailSupport': 'Email Support',
      'help.responseTime': 'Response within 24 hours',
      'help.phoneSupport': 'Phone Support',
      'help.workingHours': 'Working hours: Mon-Fri 9AM-6PM',
      'help.liveChat': 'Live Chat',
      'help.instantResponse': 'Instant response',
      'help.clickToStartChat': 'Click to start chat',

      // AI Trial
      'aiTrial.title': 'AI Content Generator',
      'aiTrial.subtitle': 'Generate high-quality content with AI',
      'aiTrial.industry': 'Industry',
      'aiTrial.contentType': 'Content Type',
      'aiTrial.generateButton': 'Generate Content',
      'aiTrial.result': 'Generated Result',
      'aiTrial.copy': 'Copy',
      'aiTrial.download': 'Download',

      // Contest
      'contest.title': 'Creative Contests', // Updated
      'contest.current': 'Current Contest',
      'contest.pastWinners': 'Past Winners',
      'contest.deadline': 'Deadline',
      'contest.prizeInfo': 'Prize Information',
      'contest.financialChallenge': 'Financial Challenge',
      'contest.challengeDescription': 'Create engaging financial content',
      'contest.firstPlace': '1st Place',
      'contest.secondPlace': '2nd Place',
      'contest.thirdPlace': '3rd Place',
      'contest.featuredOnPlatform': 'Featured on Platform',
      'contest.recognitionBadge': 'Recognition Badge',
      'contest.premiumMembership': 'Premium Membership',
      'contest.category.social_media': 'Social Media',
      'contest.category.blog_article': 'Blog Article',
      'contest.category.infographic': 'Infographic',
      'contest.category.video_content': 'Video Content',
      'contest.category.email_campaign': 'Email Campaign',
      'contest.category.podcast_script': 'Podcast Script',
      'contest.rule1': 'Original content',
      'contest.rule2': 'Theme compliance',
      'contest.rule3': 'High quality standards',
      'contest.rule4': 'Timely submission',
      'contest.rule5': 'Rule compliance',

      // Footer
      'footer.about': 'About Us',
      'footer.privacy': 'Privacy Policy',
      'footer.terms': 'Terms of Service',
      'footer.copyright': 'All rights reserved',

      'financialPlanning.retirementPeriod': 'Retirement Period',
      'financialPlanning.longTerm': 'Long Term',
      'financialPlanning.workingPeriod': 'Working Period',
    }
  };

  const t = (key, params = {}) => {
    let translation = translations[language]?.[key] || translations['en']?.[key] || key;
    
    // Replace parameters
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{${param}}`, params[param]);
    });
    
    return translation;
  };

  const toggleLanguage = () => {
    const newLang = language === 'zh-TW' ? 'en' : 'zh-TW';
    setLanguage(newLang);
    localStorage.setItem('language', newLang);
  };

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}; 